### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by Aka-DoctorCode** [AlexHaible/BetterBags-CraftingLegendaries#1]
Message: ...rface/AddOns/BetterBags-CraftingLegendaries/main.lua:86: attempt to call global 'killOldCategories' (a nil value)
Time: Sat Aug 10 03:13:49 2024
Count: 1
Stack: ...rface/AddOns/BetterBags-CraftingLegendaries/main.lua:86: attempt to call global 'killOldCategories' (a nil value)
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <...ce/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = false
 baseName = "BetterBags-CraftingLegendaries"
 moduleName = "CraftingLegendaries"
 defaultModuleState = true
 name = "BetterBags_CraftingLegendaries"
 orderedModules = <table> {
 }
}

**Comment by AlexHaible** [comment]
This has been fixed (a while ago, even, whoops)
